sudo: required
dist: trusty
language: ruby

before_install:
before_install:
- gem install asciidoctor -v 1.5.2
- gem install tilt
- sudo pip install git+https://github.com/gitenberg-dev/gitberg
- sudo pip install pillow
- sudo pip install cssutils
- sudo pip install docutils
- sudo pip install roman
- sudo pip install git+https://github.com/gitenberg-dev/pg-epubmaker
script:
- VERSION=`ruby -e "require 'yaml'; meta = YAML.load_file('metadata.yaml'); puts meta['_version'];"`
- git clone https://github.com/gitenberg-dev/asciidoctor-htmlbook.git
- sudo pip install -r asciidoctor-htmlbook/gitberg-machine/requirements.txt

- /usr/bin/python -c "from gitenberg import travis; travis.build_epub()"
- ebook-convert book.epub book.mobi
- xvfb-run ebook-convert book.epub book.pdf
branches:
  only:
  - master
notifications:
  webhooks:
    urls:
      - https://unglue.it/api/travisci/webhook
    on_success: always
    on_failure: never
    on_start: never
deploy:
  skip_cleanup: true
  provider: releases
  api_key:
    secure: CS8ZsA0Hz8e00LstvyEg/1dpFVEy+ZwmnWRUR+iNTgO1H44onINIH7JICNx+3w934u/dnxch+kXjof4yh+gE7KS73IRkOtCwmIYbLmTgVEzQ8ItpmvDfgRQqRkCKJ0dhKECaQV4feFKh3HRdWBI+6p7tn5DFMEE0zxVMMMqPcVfoPdaFPHrnDpxSyFhy/er4dr2UEJIQ0Mt/jydnhDP7jnxYaJLwxDM82QMAHsKv3AbpebbvZYUxShmvlFHO+i/sqLEVHxYw9Ee5H45LBRbhf6li8My9fqU1iQ0Ct1Fzv6N5bSmGJRw3HsYntXCVFq1M+DyElKaUbiPnGoBx+nhTk3MKWnCExNKlyTbWMaxXGW+Tqoi1veFFm3bDZFniCm3tn9rzJmNY5JA0awppTeezyHld6gbtiingUvG7orQMJs4pGAd3VPTwYVN3J+hnibfXwl6ynWxlF8tutdooN2UnTkGi9Hg80Iy7waI4FTq9Kj6JDaQsBLBBxSfehmpOshF3b3V4ArvCRPzneeWOsjUeKGxIYJ6SDhRhiy5x7zW7Kyj86M13FyCZqVMX2jaSLcGMG0Dfo2ok6vLMi8w4p4Ngw2jht1Y9XPGxD2M0eUrGxrTndIsgqK7ieZ8/9YR9vA8mN7ujQoF54isjpzGZi3n0zpoI3cRvpysGc9ecVxEeRPc=
  file:
    - book.epub
    - book.mobi
    - book.pdf
  "on":
    repo: GITenberg/The-Right-of-Way-Volume-04_6246
addons:
  apt:
    packages:
    - xsltproc
    - xvfb
    - calibre
    - python-pip
    - git
    - python-dev
    - libjpeg-dev
    - libpng-dev
    - libfreetype6
    - libfreetype6-dev
    - zlib1g-dev
    - python-lxml
    - libxml2-dev
    - libxslt1-dev
    - tidy